import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { UserProvider } from '../context/userContext'
import { Roboto } from 'next/font/google'
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'], // Specify the weights you need
})
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <div className={roboto.className}>
                    <UserProvider>{children}</UserProvider>
                </div>
            </body>
        </html>
    )
}
